name: Publish Kotlin Library

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set VERSION env var from tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: shadowJar

      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
